# Generated by Django 2.2.1 on 2019-05-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polldata',
            name='user_agent',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
