# Generated by Django 2.2.1 on 2019-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0002_polldata_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='polldata',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
