# Generated by Django 2.2.1 on 2019-05-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0003_polldata_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polldata',
            name='answer',
            field=models.CharField(max_length=256),
        ),
    ]
