# Generated by Django 2.2.1 on 2019-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0004_auto_20190531_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='polldata',
            name='answer',
            field=models.CharField(max_length=512),
        ),
        migrations.CreateModel(
            name='AudioSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples', models.ManyToManyField(to='data_collector.AudioSample')),
            ],
        ),
    ]
