# Generated by Django 2.2.1 on 2019-06-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0005_auto_20190603_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosample',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='audioset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='polldata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
