# Generated by Django 2.2.1 on 2019-06-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0006_auto_20190604_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polldata',
            name='assigned_set_id',
        ),
        migrations.AddField(
            model_name='polldata',
            name='assigned_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_collector.AudioSet'),
            preserve_default=False,
        ),
    ]
